### ISSUE TITLE
Allow all model parts to fetch stuff

### ISSUE THREAD

**Issue by cifkao** [ufal/neuralmonkey#304]
Each part of the model should be able to fetch some intermediate values from the graph and process them. For example, @obo wants to save soft alignment matrices to a file; the only sane place to put this feature is the decoder itself, but right now, the decoder can only feed tensors, not fetch them.

I propose the following:
1. Add a method `fetches(train: bool, ...?)` to `ModelPart` or modify `feed_dict()` so that it can return a list (or a nested list, dict, etc.) of tensors to fetch.
2. Add a method `batch_done(fetches, train: bool, ...?)`, which will get called by `TensorFlowManager` after each batch, with the fetches evaluated.

**Comment by jindrahelcl** [comment]
I believe that's what runners are for. This is the idea behind runners and model parts:

* `ModelPart` is a named piece of the computational graph. Since the graph can contain placeholders, model parts are responsible for supplying the values for the placeholders (it could have been done in runners and trainers as well, but it would lead to code duplication). Model parts are designed to be session-agnostic, i.e. they do not store any actual values of their tensors.
* `Runner` is an object that uses a TensorFlow session to extract values from tensors defined by a model part. Runners can also define additional tensors as well (for a trivial example, see e.g. `runner.py` lines 32 and 33), but we don't have yet decided/specified when and how. The important thing the runner does is to create an `Executable` object, that has these two methods:

* `next_to_execute` - returns model parts to feed, fetches, and additional feed dictionaries not created by the model parts (useful for overriding tensor values)
* `collect_results` - gets a list of results for each session (think ensembles) and does whatever it wants with them.

Beside these two methods, the runner also have a property `result`, which is usually set in the `collect_results` method.

The important part is that when the `runner.result` is `None`, the `next_to_execute` method is called again and again, until the `result` is set.

Back to your proposal:

1. Adding a simple runner that returns `decoder.alignment_something_something` in its executable's `next_to_execute` method does the trick. Look at `runner.py` or `rnn_runner.py` to find out how it can be done.
2. In the executable of the new runner, in the `collect_results` method, set `self.result` to something like this:
```python
self.result = ExecutionResult(
  outputs=attentions_something_something,
  losses=[],
  scalar_summaries=None,
  histogram_summaries=None,
  image_summaries=None)
``` 

Please look if this approach suits you and say if there is something unclear.

**Comment by cifkao** [comment]
Thanks, I guess that makes sense, although from a user perspective, it would be great if I could just add an option like `save_alignments="file.txt"` to the decoder in the config.

So there's no problem if two runners share a decoder?

**Comment by cifkao** [comment]
One thing I forgot about: I want to save the attention only during runtime and only on the validation dataset. How do I check that?

**Comment by jindrahelcl** [comment]
The Tensorflow manager first collects all the fetches from all the runners and then preforms a single `session.run`, so there is no problem (at least I can't see it :smile: ) with using multiple runners with one models - there is no loss of computation when for example the two runners need the same tensor. 

----
Teď si budu vymejšlet - runner má něco jako output_series. Když dáš do validačního datasetu tadyten identifikátor s předponou `s_` a příponou `_out` a dáš tomu nějakej soubor, tak by to možná mohlo fungovat zadarmo. Kdyby to nešlo, jiná věc, která se dá zneužít, je `compute_losses` argument, kterej dostává `runner.get_executable()`, a kterej je True právě při validaci. Ale zkusil bych jít cestou `output_series` runneru - teď jsem koukal do kódu, a mělo by to jít. Takže konfigurák nějak takhle:

```ini
[val_dataset]
s_source="path/to/source.txt"
s_target="path/to/target.txt"
s_target_out="path/to/output/target.out"
s_alignment_out="path/to/output/alignment.out"

; (...)

[alignment_runner]
class=runners.alignment_runner.AlignmentRunner
decoder=<decoder>
output_series="alignment"
postprocess=<jestli_chceš>
```

@jlibovicky  prosim zkontroluj jestli nemelu blbosti :-)

**Comment by jindrahelcl** [comment]
jedna věc, která tam neni je ukládání výstupních souborů po každý validaci. To kontroluje `write_out` funkce `learning_utils.run_on_dataset` a to se nastavuje na `True` až po skončení trénování a taky jen pro `test_datasets`. Oedituju ten předchozí koment, aby to tam bylo vidět

**Comment by cifkao** [comment]
To je dobrej nápad, díky. Do těch `outputs` teda můžu dát normálně seznam numpy matic (nebo jeden 3D numpy array?) a ony se nějak rozumně uloží?

**Comment by jindrahelcl** [comment]
Máš štěstí - když je to numpy array, tak to použije `np.save`, jinak to předpokládá, že je to seznam seznamů stringů (vět).

**Comment by cifkao** [comment]
To nefunguje, protože když se dá do `outputs` numpy array, tak tf_manager z toho udělá seznam numpy arrayů.

**Comment by jindrahelcl** [comment]
Tak nevim, co když dáš pole numpy arrayů (v batchi)?

**Comment by cifkao** [comment]
To dopadne stejně. `reduce_execution_results` to appendí k prázdnému seznamu, takže je z toho pak seznam arrayů. Můžu tam dopsat, aby se to v takovém případě sloučilo do jednoho. (Seznam arrayů do jednoho souboru asi zapsat rozumně nejde.)

**Comment by jindrahelcl** [comment]
Ono je možný, že `reduce_execution_results` se nechová tak, jak má.. Koukám do toho a přijde mi, že je to kvůli tomu, aby tam nebyl jeden tenzor víckrát, ale nevim...

**Comment by jlibovicky** [comment]
`reduce_execution_results` totiž zapomnělo počítat s tím, že tam můžou být numpy tenzory. Ale to se snadno spraví.
