### ISSUE TITLE
what's kind of source code editor used for this project?

### ISSUE THREAD

**Issue by loveJasmine** [ufal/neuralmonkey#468]
It looks very chaos in my Pycharm, and the 'code reformat' function doesn't works

**Comment by jindrahelcl** [comment]
A vast majority of the code was written in Emacs or Vim. @tomkocmi uses Pycharm. However, the code conforms to the PEP-8 style guide.

**Comment by tomkocmi** [comment]
There is a lot of minor problems with PEP8 and we use pylint to check it which do not check the PEP8 perfectly (and also it have a lot of bugs). The pycharm format a code in a slightly different way which also isn't always PEP8.

Another issue is some internal decision about the maximal length of a row 79 characters and how to intent multiline commands which do not fit to one line.

I am using the pycharm, but sadly because of those differences, I am forced not to use it for formatting the code. Maybe one day I'll be able to convince my colleagues to change some of the inconsistencies in the format or at least pylint will resolve some of its bugs :).
