### ISSUE TITLE
ValueError("Vocabulary file do not have two columns")

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [ufal/neuralmonkey#566]
Hi,

I got this when using vocabulary.initialize_vocabulary.  It seems it doesn't recognize the tabulator:
https://github.com/StoyanVenDimitrov/neuralmonkey/blob/mrt_annealing/neuralmonkey/vocabulary.py#L82

Any idea how to solve it?

Best,
Stoyan

**Comment by jindrahelcl** [comment]
what format is your vocabulary? We changed the format to tab-separated values instead of an pickled python object.

also, prefer not to use the `initialize_vocabulary` function. Use either `vocabulary.from_dataset` which can store the vocabulary to file, or `vocabulary.from_wordlist` which then loads this file.

**Comment by StoyanVenDimitrov** [comment]
It leads to the same issue when loading with from_wordlist.

**Comment by jindrahelcl** [comment]
it seems the format of the vocabulary file is wrong. it may be either the old format (python pickle) or it may be corrupted in some way. try print out the line number in which the vocabulary intiialization fails and look into the file. may be also an encoding problem.

**Comment by StoyanVenDimitrov** [comment]
Ok, there was one line with count, but no word. I deleted it and it is fine now.

**Comment by jindrahelcl** [comment]
Thanks for reporting this, I have opened an issue to clarify the error message (#567)
