### ISSUE TITLE
 from_dataset does not exist

### ISSUE THREAD

**Issue by tomsbergmanis** [ufal/neuralmonkey#794]
Hi! 
Thank you for developing neuralmonkey! I am excited to start using it, but I ran into a problem. Following the APE tutorial I have specified:
[source_vocabulary]
class=vocabulary.from_dataset
datasets=[<train_dataset>]
series_ids=["source"]
max_size=50000

yet I get the following error suggesting that from_dataset does not exist:

![capture](https://user-images.githubusercontent.com/3306933/52918895-663a0c00-32f4-11e9-90ce-2a123eb978ab.PNG)

What have I done wrong? 
Thank you in advance! 
T.

**Comment by jindrahelcl** [comment]
Hi,

the problem is on our side - the tutorial is outdated. In recent versions
of neural monkey, you need to create the vocabulary file yourself and load
with the `vocabulary.from_wordlist` method. An example vocabulary file is
located in this repository e.g. in `tests/data/encoder_vocab.tsv`. You can
also use 3rd party tools to create the vocabulary, such as
github.com/google/sentencepiece, but then you need to match the vocabulary
format to neural monkey's (first four lines corresponding to four special
symbols). This could be done using sentencepiece's command line options
--bos-id, --unk-id, --eos-id, and so on...


ne 17. 2. 2019 v 21:45 odesílatel Toms Bergmanis <notifications@github.com>
napsal:

**Comment by tomsbergmanis** [comment]
Cool, thanks. I thought that it might be the case. Thank you for the prompt
reply!
