### ISSUE TITLE
Throw a warning when unknown parameter is encountered in the configuration

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#95]
Not sure if this can be done in configuration. The simple way would be to add the checking to every constructor with the **kwargs parameter. Or not to use **kwargs parameters at all.

**Comment by jlibovicky** [comment]
I think avoiding `**kwargs` everywhere we can, is the best idea. no matter what the style guides say. It is the only way we can make sure there is no typo construction of object from configuration and prevent debugging such things. The only where it is really inevitable is probably creating the datasets with the convention for series names.

Explicit checking in the configuration used to be there. But since we want strict separation of parsing and running the code in the configuration, it is not possible any more.  We cannot import the modules during the parsing because importing can mean running a code and it may prevent us from setting a fixed seed before anything happens - and importing a module is the only way to find out what parameters a function accepts. For me it is OK to pass all the arguments to the constructor and let it fail on unknown arguments in the worse case.

**Comment by jlibovicky** [comment]
What is the state of this?

**Comment by jindrahelcl** [comment]
I believe it's still not done. Try grepping kwargs from python sources to see where it should be checked.
